In [17]:
import pandas as pd
import numpy as np

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21936\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [18]:
car = pd.read_csv("C:/Users/Lenovo/Programacion/Base de datos/CarPricesPrediction.csv")
car.drop('Unnamed: 0', axis =1, inplace=True)
Honda = car['Make'] == "Honda"
Civic = car["Model"] == "Civic"
Hondacivid =car[Honda & Civic]
Hondacivid.sort_values(["Year"], ascending=True, inplace=True)
Hondacivid

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21936\1042266520.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hondacivid.sort_values(["Year"], ascending=True, inplace=True)

      Make  Model  Year  Mileage  Condition     Price
824  Honda  Civic  2010    47611  Excellent  29619.55
182  Honda  Civic  2010    29471  Excellent  30526.55
791  Honda  Civic  2010   147306       Good  24634.70
851  Honda  Civic  2011   112032  Excellent  25398.30
752  Honda  Civic  2011    77760       Good  27111.90
276  Honda  Civic  2011   117131       Good  25143.45
351  Honda  Civic  2011    51775  Excellent  28411.35
63   Honda  Civic  2012    99506  Excellent  25024.70
807  Honda  Civic  2012    48331  Excellent  27583.55
860  Honda  Civic  2014    10120  Excellent  27494.10
787  Honda  Civic  2014    34734       Fair  26263.30
346  Honda  Civic  2014   131078       Fair  21446.20
641  Honda  Civic  2014    17168       Good  27141.60
341  Honda  Civic  2015   146704  Excellent  19664.90
777  Honda  Civic  2015   122879  Excellent  20856.15
280  Honda  Civic  2015   143862  Excellent  19806.90
297  Honda  Civic  2016   118154       Good  20092.30
80   Honda  Civic  2016    27511  Excellent  24624.45
933  Honda  Civic  2016    38708  Excellent  24064.70
795  Honda  Civic  2017    94183  Excellent  20290.85
625  Honda  Civic  2017    96018  Excellent  20199.20
979  Honda  Civic  2018   103726       Good  18813.80
589  Honda  Civic  2018    27846  Excellent  22607.60
556  Honda  Civic  2018   136822  Excellent  17159.00
548  Honda  Civic  2018    78256  Excellent  20087.30
869  Honda  Civic  2018    55849  Excellent  21207.65
840  Honda  Civic  2019    30687       Fair  21465.75
177  Honda  Civic  2019    49430  Excellent  20528.50
870  Honda  Civic  2019   115299  Excellent  17235.05
542  Honda  Civic  2020    28846       Fair  20557.80
823  Honda  Civic  2021   136606       Good  14169.60
732  Honda  Civic  2021    84577  Excellent  16771.05
28   Honda  Civic  2022    34080  Excellent  18296.00
558  Honda  Civic  2022   110420       Good  14479.10
49   Honda  Civic  2022    17332  Excellent  19133.50
582  Honda  Civic  2022   142482  Excellent  12875.90
593  Honda  Civic  2022    98546       Good  15072.70

## Info()

With this command we can see all the info about our dataframe, like Index's number, Detail by columns, dtype.

In [37]:
Hondacivid.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 824 to 593
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Make       37 non-null     object
 1   Model      37 non-null     object
 2   Year       37 non-null     int64
 3   Mileage    37 non-null     int64
 4   Condition  37 non-null     object
 5   Price      37 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 2.0+ KB

## Descibe()

We can see all kind of stad information such as mean, min, max, count, Std , by columns

In [38]:
Hondacivid.describe()

              Year        Mileage         Price
count    37.000000      37.000000     37.000000
mean   2016.216216   80076.918919  21779.972973
std       3.916739   44631.973778   4522.788369
min    2010.000000   10120.000000  12875.900000
25%    2014.000000   34734.000000  19133.500000
50%    2016.000000   84577.000000  20856.150000
75%    2019.000000  117131.000000  25143.450000
max    2022.000000  147306.000000  30526.550000

## Tail()

Returns the last register in our dataframe

In [25]:
Hondacivid.tail(3)

      Make  Model  Year  Mileage  Condition    Price
49   Honda  Civic  2022    17332  Excellent  19133.5
582  Honda  Civic  2022   142482  Excellent  12875.9
593  Honda  Civic  2022    98546       Good  15072.7

## Drop.duplicate()

Eliminate the duplicated data in the dataframe. Ex:

In [30]:
new  = Hondacivid.loc[49]

In [32]:
pd.concat([Hondacivid, new])

            Make  Model    Year   Mileage  Condition     Price         49
824        Honda  Civic  2010.0   47611.0  Excellent  29619.55        NaN
182        Honda  Civic  2010.0   29471.0  Excellent  30526.55        NaN
791        Honda  Civic  2010.0  147306.0       Good  24634.70        NaN
851        Honda  Civic  2011.0  112032.0  Excellent  25398.30        NaN
752        Honda  Civic  2011.0   77760.0       Good  27111.90        NaN
276        Honda  Civic  2011.0  117131.0       Good  25143.45        NaN
351        Honda  Civic  2011.0   51775.0  Excellent  28411.35        NaN
63         Honda  Civic  2012.0   99506.0  Excellent  25024.70        NaN
807        Honda  Civic  2012.0   48331.0  Excellent  27583.55        NaN
860        Honda  Civic  2014.0   10120.0  Excellent  27494.10        NaN
787        Honda  Civic  2014.0   34734.0       Fair  26263.30        NaN
346        Honda  Civic  2014.0  131078.0       Fair  21446.20        NaN
641        Honda  Civic  2014.0   17168.0       Good  27141.60        NaN
341        Honda  Civic  2015.0  146704.0  Excellent  19664.90        NaN
777        Honda  Civic  2015.0  122879.0  Excellent  20856.15        NaN
280        Honda  Civic  2015.0  143862.0  Excellent  19806.90        NaN
297        Honda  Civic  2016.0  118154.0       Good  20092.30        NaN
80         Honda  Civic  2016.0   27511.0  Excellent  24624.45        NaN
933        Honda  Civic  2016.0   38708.0  Excellent  24064.70        NaN
795        Honda  Civic  2017.0   94183.0  Excellent  20290.85        NaN
625        Honda  Civic  2017.0   96018.0  Excellent  20199.20        NaN
979        Honda  Civic  2018.0  103726.0       Good  18813.80        NaN
589        Honda  Civic  2018.0   27846.0  Excellent  22607.60        NaN
556        Honda  Civic  2018.0  136822.0  Excellent  17159.00        NaN
548        Honda  Civic  2018.0   78256.0  Excellent  20087.30        NaN
869        Honda  Civic  2018.0   55849.0  Excellent  21207.65        NaN
840        Honda  Civic  2019.0   30687.0       Fair  21465.75        NaN
177        Honda  Civic  2019.0   49430.0  Excellent  20528.50        NaN
870        Honda  Civic  2019.0  115299.0  Excellent  17235.05        NaN
542        Honda  Civic  2020.0   28846.0       Fair  20557.80        NaN
823        Honda  Civic  2021.0  136606.0       Good  14169.60        NaN
732        Honda  Civic  2021.0   84577.0  Excellent  16771.05        NaN
28         Honda  Civic  2022.0   34080.0  Excellent  18296.00        NaN
558        Honda  Civic  2022.0  110420.0       Good  14479.10        NaN
49         Honda  Civic  2022.0   17332.0  Excellent  19133.50        NaN
582        Honda  Civic  2022.0  142482.0  Excellent  12875.90        NaN
593        Honda  Civic  2022.0   98546.0       Good  15072.70        NaN
Make         NaN    NaN     NaN       NaN        NaN       NaN      Honda
Model        NaN    NaN     NaN       NaN        NaN       NaN      Civic
Year         NaN    NaN     NaN       NaN        NaN       NaN       2022
Mileage      NaN    NaN     NaN       NaN        NaN       NaN      17332
Condition    NaN    NaN     NaN       NaN        NaN       NaN  Excellent
Price        NaN    NaN     NaN       NaN        NaN       NaN    19133.5

In [33]:
Hondacivid.drop_duplicates()

      Make  Model  Year  Mileage  Condition     Price
824  Honda  Civic  2010    47611  Excellent  29619.55
182  Honda  Civic  2010    29471  Excellent  30526.55
791  Honda  Civic  2010   147306       Good  24634.70
851  Honda  Civic  2011   112032  Excellent  25398.30
752  Honda  Civic  2011    77760       Good  27111.90
276  Honda  Civic  2011   117131       Good  25143.45
351  Honda  Civic  2011    51775  Excellent  28411.35
63   Honda  Civic  2012    99506  Excellent  25024.70
807  Honda  Civic  2012    48331  Excellent  27583.55
860  Honda  Civic  2014    10120  Excellent  27494.10
787  Honda  Civic  2014    34734       Fair  26263.30
346  Honda  Civic  2014   131078       Fair  21446.20
641  Honda  Civic  2014    17168       Good  27141.60
341  Honda  Civic  2015   146704  Excellent  19664.90
777  Honda  Civic  2015   122879  Excellent  20856.15
280  Honda  Civic  2015   143862  Excellent  19806.90
297  Honda  Civic  2016   118154       Good  20092.30
80   Honda  Civic  2016    27511  Excellent  24624.45
933  Honda  Civic  2016    38708  Excellent  24064.70
795  Honda  Civic  2017    94183  Excellent  20290.85
625  Honda  Civic  2017    96018  Excellent  20199.20
979  Honda  Civic  2018   103726       Good  18813.80
589  Honda  Civic  2018    27846  Excellent  22607.60
556  Honda  Civic  2018   136822  Excellent  17159.00
548  Honda  Civic  2018    78256  Excellent  20087.30
869  Honda  Civic  2018    55849  Excellent  21207.65
840  Honda  Civic  2019    30687       Fair  21465.75
177  Honda  Civic  2019    49430  Excellent  20528.50
870  Honda  Civic  2019   115299  Excellent  17235.05
542  Honda  Civic  2020    28846       Fair  20557.80
823  Honda  Civic  2021   136606       Good  14169.60
732  Honda  Civic  2021    84577  Excellent  16771.05
28   Honda  Civic  2022    34080  Excellent  18296.00
558  Honda  Civic  2022   110420       Good  14479.10
49   Honda  Civic  2022    17332  Excellent  19133.50
582  Honda  Civic  2022   142482  Excellent  12875.90
593  Honda  Civic  2022    98546       Good  15072.70